import { DiamondsCard } from './helpers'

export const aceOfDiamonds = new DiamondsCard(1)
export const twoOfDiamonds = new DiamondsCard(2)
export const threeOfDiamonds = new DiamondsCard(3)
export const fourOfDiamonds = new DiamondsCard(4)
export const fiveOfDiamonds = new DiamondsCard(5)
export const sixOfDiamonds = new DiamondsCard(6)
export const sevenOfDiamonds = new DiamondsCard(7)
export const eightOfDiamonds = new DiamondsCard(8)
export const nineOfDiamonds = new DiamondsCard(9)
export const tenOfDiamonds = new DiamondsCard(10)
export const jackOfDiamonds = new DiamondsCard(11)
export const queenOfDiamonds = new DiamondsCard(12)
export const kingOfDiamonds = new DiamondsCard(13)